services:
  - type: web
    name: carwash-api
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader && php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: carwash-db
          property: connectionString

databases:
  - name: carwash-db
    plan: free
    databaseName: carwash
    user: carwash_user